### PR TITLE
Update device detail and create device page layout

### PR DESCRIPTION
**Pull request by kbeaugrand**
## Description

What's new?

- Update layout for device details and device models
- Enhance image avatar upload
- Enhance device model commands manipulation

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Checklist before merge

**Developer's responsibilities**
- [x] This pull request merges to `main`
- [x] Approved by at least one developer
- [x] **Pull request build** has passed
- [x] Staging app has been deployed successfully

**Product Owner's responsibilities**
- [x] No issues have been found on staging environment
- [x] Product Owner has approved the release

### CODE REVIEW

**Comment by kbeaugrand** [comment]
Hi, Here are some new screens: 

## Device Details
image

## Device Model Details

image

What do you think about it ?

**Review by Sben65 — COMMENTED** [review]
in the CreateDeviceModelPage, if the user uploads an image but cancels the model creation, what happens to the uploaded image?

**Comment by kbeaugrand** [comment]
Hi @Sben65, 

Well, you're right, the image remains in the storage account yet. 
Could we create another issue to destroy uploaded images that are not needed anymore ?

**Comment by Sben65** [comment]
for sure.

**Review by Sben65 — APPROVED** [review]

**Pull request merged**
